# Generated by Django 5.1.5 on 2025-01-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Movie',
        ),
    ]
